name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build in Amazon Linux Container
      run: |
        docker run --rm -v $(pwd):/lambda-build -w /lambda-build \
          amazonlinux:2023 /bin/bash -c "
          yum install -y python3.12 python3.12-pip zip &&
          python3.12 -m pip install poetry && poetry self add poetry-plugin-export &&
          poetry export -f requirements.txt --without-hashes -o requirements.txt &&
          mkdir -p package &&
          python3.12 -m pip install --target package -r requirements.txt &&
          cd package &&
          zip -r ../function.zip . &&
          cd ../src &&
          zip -g -r ../function.zip .
        "

        # Build monthly reports function package
        docker run --rm -v $(pwd):/lambda-build -w /lambda-build \
          amazonlinux:2023 /bin/bash -c "
          yum install -y python3.12 python3.12-pip zip &&
          python3.12 -m pip install poetry && poetry self add poetry-plugin-export &&
          poetry export -f requirements.txt --without-hashes -o requirements.txt &&
          mkdir -p package-monthly-reports &&
          python3.12 -m pip install --target package-monthly-reports -r requirements.txt &&
          cd package-monthly-reports &&
          zip -r ../monthly-reports-function.zip . &&
          cd ../src &&
          zip -g -r ../monthly-reports-function.zip .
        "

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      run: |
        aws s3 cp function.zip s3://${{vars.LAMBDA_PACKAGE_BUCKET}}/process_txn_email.zip
        aws s3 cp monthly-reports-function.zip s3://${{vars.LAMBDA_PACKAGE_BUCKET}}/monthly_reports_function.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      run: |
        # Deploy process-txn-email function
        aws lambda update-function-code \
          --function-name process-txn-email \
          --s3-bucket pennywise-lambda-deploy \
          --s3-key process_txn_email.zip


        echo "Updating generate-monthly-reports function..."
        aws lambda update-function-code \
            --function-name generate-monthly-reports \
            --s3-bucket pennywise-lambda-deploy \
            --s3-key monthly_reports_function.zip \
            --region ${{ vars.AWS_REGION }}

        # Wait for the function code update to complete before updating configuration
        echo "Waiting for function code update to complete..."
        aws lambda wait function-updated \
            --function-name generate-monthly-reports \
            --region ${{ vars.AWS_REGION }}

        # Set environment variables for the monthly reports function
        aws lambda update-function-configuration \
          --function-name generate-monthly-reports \
          --environment Variables='{GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}",TXN_EMAILS_BUCKET_NAME="${{ vars.TXN_EMAILS_BUCKET_NAME }}",TXN_TABLE_NAME="${{ vars.TXN_TABLE_NAME }}",REGION="${{ vars.AWS_REGION }}",REPORTS_S3_BUCKET="${{ vars.REPORTS_S3_BUCKET }}"}'
